# Generated by Django 3.2 on 2021-05-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('followerCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30, unique=True)),
                ('follows', models.ManyToManyField(blank=True, to='landing.TwitterUser')),
            ],
        ),
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FROM', to='landing.twitteruser')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO', to='landing.twitteruser')),
            ],
        ),
    ]
