# Generated by Django 3.2 on 2021-04-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='followerCount',
            field=models.IntegerField(default=0),
        ),
    ]
