# Generated by Django 3.2.3 on 2021-05-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_twitteruser_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='connections',
            name='follows',
            field=models.BooleanField(default=False),
        ),
    ]
