# Generated by Django 3.2 on 2021-05-05 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_twitteruser_followercount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FROM', to='landing.twitteruser')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO', to='landing.twitteruser')),
            ],
        ),
    ]
